### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by himadrinath** [lucas-gaitzsch/pdf-turtle#7]
@lucas-gaitzsch  take a look at this [html](https://codesandbox.io/s/pdf-turtle-66r2xz?file=/index.html) page in print preview getting every page,
but in pdf-turtle playground only getting first page.
if i delete height & width then getting all the pages but the header is not repeating in every page

```
@media print { 
  body{
    counter-reset: page;
    margin: 0 auto;
    width: 210mm;
    height: 297mm;
  }
}
```

**Comment by lucas-gaitzsch** [comment]
I would recommend you to use the header and footer sections (see header and footer tab in the playground). 

I think your problem is the hight of 100% in combination with `overflow: hidden`. 
See: [default-pdf-styles.css](https://github.com/lucas-gaitzsch/pdf-turtle/blob/main/static-files/embed/default-pdf-styles.css)

**Comment by lucas-gaitzsch** [comment]
@himadrinath Were you able to solve your problem?

**Comment by himadrinath** [comment]
Yes solve it
